### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by tobimori** [johannschopplich/kirby.tools#1]
### Environment

Kirby 4.1.2 + Kirby Tools 1.0.5
Chrome 123, macOS Sonoma 14.3.1

### Describe the bug

![CleanShot 2024-03-23 at 23 07 47@2x](https://github.com/johannschopplich/kirby.tools/assets/29142128/5fc0cbe1-548e-4e3c-ae08-dec6f41dd8fd)
Inside the live preview

Expected output
![CleanShot 2024-03-23 at 23 08 29@2x](https://github.com/johannschopplich/kirby.tools/assets/29142128/f05131d0-6181-4feb-856d-cccd973b9bef)

**Comment by johannschopplich** [comment]
Thanks a lot for the report! The encoding issue should be fixed with v1.0.6. 

You can then download the latest version from your [order page](https://app.lemonsqueezy.com/my-orders) of our payment provider.

**Comment by tobimori** [comment]
Fixed, thanks!
