### ISSUE TITLE
Follow permalinks / redirected URLs if they're local

### ISSUE THREAD

**Issue by tobimori** [johannschopplich/kirby.tools#4]
### Describe the feature

When using the Writer field, it's common to have permalinks in the sites' code. It'd be awesome if they could work as well with the preview -> link in panel thing. But it's mindblowing even at it's current state :)

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/kirby.tools/issues).

**Comment by johannschopplich** [comment]
Glad to hear you enjoy the link redirects (haven't found a suiting feature name for myself).

Sure thing! This has been implemented in [v1.1.0+](https://kirby.tools/docs/live-preview/changelog).
