### ISSUE TITLE
Rearranging images does not refresh live preview until another field is edited

### ISSUE THREAD

**Issue by Thiousi** [johannschopplich/kirby.tools#8]
### Environment

kirby.tools demo

### Describe the bug

1. Navigate to a page with images (e.g. https://play.kirby.tools/panel/pages/photography+trees)
2. Reorder images. 
3. Check preview: order is unchanged.
4. Edit another field
5. Check preview: order of images is changed.

**Comment by johannschopplich** [comment]
Thanks a lot for the bug report! You're right, the Panel section wasn't listening on the `file.sort` event. Somehow, Kirby handles sort updates not as content updates.

Will be released with the next minor or patch version. Until then, the playground has been updated to the canary release.

I will leave this issue open to notify you when the version has been released.

**Comment by johannschopplich** [comment]
This has been fixed in v1.2.1.
