### ISSUE TITLE
Private composer server

### ISSUE THREAD

**Issue by tobimori** [johannschopplich/kirby.tools#9]
### Describe the feature

I use composer for all plugins and it's a hassle to manually keep track of updates and then replace the code in each sites repository when I could just run composer install.

Simple version: https://github.com/composer/satis
-> staticly generated, auth via HTTP basic auth

Fancy/complex version: https://github.com/vtsykun/packeton

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/kirby.tools/issues).

**Comment by johannschopplich** [comment]
Currently in development. 🤗
